spring.application.name=ms-pagamento

spring.profiles.active=test
spring.jpa.open-in-view=false
spring.flyway.enabled=false

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

server.port=0

eureka.instance.instance-id=${spring.application.name}:${random.int[1,99]}

resilience4j.circuitbreaker.instances.atualizarPedido.slidingWindowSize=3

resilience4j.circuitbreaker.instances.atualizarPedido.slidingWindowType=COUNT_BASED

resilience4j.circuitbreaker.instances.atualizarPedido.minimumNumberOfCalls=2

resilience4j.circuitbreaker.instances.atualizarPedido.failureRateThreshold=50

resilience4j.circuitbreaker.instances.atualizarPedido.waitDurationInOpenState=50s